import { v4 as uuid } from "uuid";
export const videos = [
  {
    _id: uuid(),
    title: "Preferred Gender Pronouns: What are they?",
    description:
      "Learn about Preferred Gender Pronouns (PGP's) and how understanding them plays a vital role in being inclusive in the workplace and out.",
    creator: "ADP",
    imageURL:"https://img.youtube.com/vi/-_VJ9m3yajU/maxresdefault.jpg",
    timeStamp:"2:57",
    views:"32k",
    uploadDate:"Feb 25, 2020",
    videoURL:"https://www.youtube.com/watch?v=-_VJ9m3yajU",
    blueTick:true,
    subscribers:"20.7k",
    categoryName:"LGBTQ+ Ed",
    channelImg:"https://yt3.ggpht.com/MTwwXxq0eufDF8gQPhmaAcEn5z1wHx4_ncHc2dKn2jhU4GRVYKZiNnf1piTg2rcGPdbQOAaS=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "Wanda Sykes Takes Us Through the History of LGBTQ+ — Now You Know",
    description:
      "Have you ever wondered about the beginnings of homosexuality? Get to know a little bit about the fight for equality as Wanda Sykes takes us on a journey all the way back to the Middle Ages. Now, in 2019, we get to celebrate moments like Pride Month in June and Transgender Awareness Week in November.",
    creator: "TheEllenShow",
    imageURL:"https://img.youtube.com/vi/wkzwDOCEDCo/maxresdefault.jpg",
    timeStamp:"4:31",
    views:"5M",
    uploadDate:"Nov 14, 2019",
    videoURL:"https://www.youtube.com/watch?v=wkzwDOCEDCo",
    blueTick:true,
    subscribers:"38.2M",
    categoryName:"LGBTQ+ Ed",
    channelImg:"https://yt3.ggpht.com/I0j6g1bOYmGniEtkySB7tmvHxmo5InW1gqGRZJfFT_ErwZbRMKATBkUQyYutEPTB2A-Z2C0Z6w=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "Gender Identity and Pronouns - Onlea - What Will You Teach The World?",
    description:
      "We asked some people in our community a simple question, What will you teach the world?Gender Identity and Pronouns with Tristan from the Pride Centre of Edmonton.",
    creator: "Onlea",
    imageURL:"https://img.youtube.com/vi/J3Fh60GEB5E/maxresdefault.jpg",
    timeStamp:"3:42",
    views:"1.7M",
    uploadDate:"Jun 7, 2017",
    videoURL:"https://www.youtube.com/watch?v=J3Fh60GEB5E",
    blueTick:false,
    subscribers:"485",
    categoryName:"LGBTQ+ Ed",
    channelImg:"https://yt3.ggpht.com/m-XS9n7unVvR6I4YL1glgO88dTOHf1nCBuhsIzp2M0QoNQYDmAFIqMTEeAogePohW86orhueRw=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "A global history of women's rights, in 3 minutes",
    description:
      "How much progress have we achieved in the global struggle for equal rights, and how much work remains? From worldwide suffrage campaigns to the rise of #MeToo and digital activism, we have marched slowly forward. But today, the fight for gender equality is far from over. Discover the noteworthy women, grassroots movements and historic milestones that have changed the world for women and girls.",
    creator: "UN Women",
    imageURL:"https://img.youtube.com/vi/m_UjYOfmkn8/maxresdefault.jpg",
    timeStamp:"3:27",
    views:"40k",
    uploadDate:"Jan 17, 2020",
    videoURL:"https://www.youtube.com/watch?v=m_UjYOfmkn8",
    blueTick:false,
    subscribers:"58.9k",
    categoryName:"Women's Rights History",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLQu6rZsXzVc6TbfRp5GgCUkA_h2e_eFX9THWBmM=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "Drawn to You - Animated Short Film",
    description:
      "Young Emily didn't see anything wrong with her drawing of two girls holding hands, but her mother saw otherwise and tore both the paper and her child's heart in two. Little did they know, the drawings had come alive and are determined to reunite with one another across the vast bedroom of pages, no matter what risk comes their way. An adventurous and heartwarming tale, “Drawn to You” shows audiences both the struggles and joy that comes with being true to your heart, and not letting others tell you who to be.",
    creator: "Drawn to You Flim",
    imageURL:"https://img.youtube.com/vi/5mDKO-AdnGk/maxresdefault.jpg",
    timeStamp:"4:34",
    views:"6.4M",
    uploadDate:"2019",
    videoURL:"https://www.youtube.com/watch?v=5mDKO-AdnGk",
    blueTick:false,
    subscribers:"48.7k",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLSedwzZ8mo0KRMMzMwBNcmpLKmwWX7sivvkZVpT=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "CGI Animated Short Film 'In a Heartbeat' by Beth David and Esteban Bravo | CGMeetup",
    description:
      "'In a Heartbeat' - Animated Short Film by Beth David and Esteban Bravo.A closeted boy runs the risk of being outed by his own heart after it pops out of his chest to chase down the boy of his dreams.",
    creator: "CGMeetup",
    imageURL:"https://img.youtube.com/vi/sAaqLIsOmCE/maxresdefault.jpg",
    timeStamp:"4:05",
    views:"24M",
    uploadDate:"Aug 3, 2017",
    videoURL:"https://www.youtube.com/watch?v=sAaqLIsOmCE",
    blueTick:false,
    subscribers:"5.81",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLSY6qwuYPedEmg8dnjXanUIUWB5PulvDRkY9n0vWLM=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "A Brief History of Women's Rights",
    description:"A Fixer from Cardiff, 17, thinks more needs to be done to ensure women everywhere enjoy equal rights. She's using this film to celebrate progress already made, while continuing the campaign for gender equality.",
    creator: "Fixers UK",
    imageURL:"https://img.youtube.com/vi/gpU0c15coBU/maxresdefault.jpg",
    timeStamp:"3:06",
    views:"10k",
    uploadDate:"May 27, 2014",
    videoURL:"https://www.youtube.com/watch?v=gpU0c15coBU",
    blueTick:false,
    subscribers:"11.2k",
    categoryName:"Women's Rights History",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLRa9xuvEKnBkCJp5zBaplVlaD1EclKjxBubqKpqpA=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "Being Not Straight",
    description: "Story of Jaiden, who came out AroAce",
    creator: "Jaiden Animations",
    imageURL:"https://img.youtube.com/vi/qF1DTK4U1AM/maxresdefault.jpg",
    timeStamp:"15:21",
    views:"11M",
    uploadDate:"Mar 20, 2020",
    videoURL:"https://www.youtube.com/watch?v=qF1DTK4U1AM",
    blueTick:true,
    subscribers:"11.1M",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLRNxD6bUt19EWl0Y3_YUDYD1l3gTpmN8mQSvYYLrg=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "Cariño - Animated Short Film | LGBTQ+",
    description:
      "Santiago is perusing the streets of Cartagena when another boy catches his attention. He watches, infatuated, as the boy, Camilo, looks around the bodega. Camilo seems worried, and desperately shows the shopkeeper a photo of his Grandmother holding a Lily which he is trying to find. Dejected, Camilo turns and attempts to put the photo in his back pocket, but it misses and falls to the ground. He gets a phone call from his mother stating that he needs to find the Lily before his Grandmother's birthday party. Santiago, now worried about Camilo's state, rushes to pick up the photo and makes it his mission to find the flower Camilo was searching for.Santiago attempts multiple times to find the flower but fails until finally he spots the flower growing on a high balcony. He tries to reach for the flowers and just as he manages to grab them, he falls to the ground. This crash attracts the attention of Camilo as he approaches and helps Santiago up. Santiago is able to finally give him the flower he worked so hard to retrieve and return Camilo's photograph. Camilo is stunned at first but then touched at Santiago's dedication, and invites Santiago to walk with him.",
    creator: "Cariño Animated Short Film",
    imageURL:"https://img.youtube.com/vi/pmy2uxUCwj8/maxresdefault.jpg",
    timeStamp:"3:46",
    views:"81k",
    uploadDate:"Jul 3, 2021",
    videoURL:"https://www.youtube.com/watch?v=pmy2uxUCwj8",
    blueTick:false,
    subscribers:"733",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/mbp2Vmoj9O_wZvKe7rPOVoIuR01dLVtfiysawKpGZjv2D6B6a5eONq5P6Ih7SxlmMtcvXj6vWfU=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "The Acorn Princess | Animated Short Film",
    description:
      "Princess Cornelia and the Flower Prince have been betrothed for as long as they can remember. The two have grown inseparable...as friends. Cornelia pines for the heart of the guard captain, and the Flower Prince is involved with another in secret. On the eve of their wedding day, the pair dread what may be the end of their lives as they know it.",
    creator: "Tough Nut Studios",
    imageURL:"https://img.youtube.com/vi/bSjjD6CbUIM/maxresdefault.jpg",
    timeStamp:"7:06",
    views:"2.9M",
    uploadDate:"2021",
    videoURL:"https://www.youtube.com/watch?v=bSjjD6CbUIM",
    blueTick:false,
    subscribers:"52.8k",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLQybtyFxt0rgWFf4hRUNMLAUOb6ExgB7y6-0srI=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "The historic women's suffrage march on Washington - Michelle Mehrtens",
    description:
      "Explore how the Women's Suffrage Parade on Washington in 1913 helped women secure the right to vote in the United States through the 19th amendment.On March 3, 1913, after months of strategic planning and controversy, thousands of women gathered in Washington D.C. for the Women's Suffrage Parade -- the first mass protest for a woman's right to vote. Michelle Mehrtens details how the march rejuvenated the fight for the 19th amendment.",
    creator: "TED-Ed",
    imageURL:"https://img.youtube.com/vi/_KhYRqozTDE/maxresdefault.jpg",
    timeStamp:"4:54",
    views:"39k",
    uploadDate:"Mar 4, 2019",
    videoURL:"https://www.youtube.com/watch?v=_KhYRqozTDE",
    blueTick:true,
    subscribers:"16.6M",
    categoryName:"Women's Rights History",
    channelImg:"https://yt3.ggpht.com/HjXKmDGoAp6b-JdGYpqJYYeN4S_CMpD_kqWvldpN53cbzn-i73t6mVNo8mNki-xLPwi0BVSFi-o=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "History of the Women's Movement",
    description:
      "Women fighting for their basic rights",
    creator: "eGirl Power",
    imageURL:"https://img.youtube.com/vi/qhMatTjdgZE/maxresdefault.jpg",
    timeStamp:"3:30",
    views:"2.6k",
    uploadDate:"Aug 19, 2016",
    videoURL:"https://www.youtube.com/watch?v=qhMatTjdgZE",
    blueTick:false,
    subscribers:"524",
    categoryName:"Women's Rights History",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLQGUEps8K90cFgNmD9-SVtqSDPQSCPMonJA5RIQJg=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "LGBT Animated Infographic",
    description:
      "LGBT info and basic rules",
    creator: "Ruben Baeza",
    imageURL:"https://i.ytimg.com/vi/UG8eMgb-_Oc/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBN9msaDSFRjXhIdIxO83CPMJoAOA",
    timeStamp:"2:33",
    views:"38k",
    uploadDate:"Dec 12, 2019",
    videoURL:"https://www.youtube.com/watch?v=UG8eMgb-_Oc",
    blueTick:false,
    subscribers:"151",
    categoryName:"LGBTQ+ Ed",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLTbEGGOaAsaYutlj7Hf9FoxtUhlFXR5R3asjwh4=s48-c-k-c0x00ffffff-no-rj",
  },
  {
    _id: uuid(),
    title: "BOY BI • oc animatic 【Little Pickle Town】",
    description:
      "Leo Peterson claims that he doesn't have time to prioritize romance when simply, he was just used to being rejected by love interests. But now that he's being asked out by MADAME'S jazz pianist and singer... what goes next?",
    creator: "anana alog",
    imageURL:"https://img.youtube.com/vi/C48-6GopS1c/maxresdefault.jpg",
    timeStamp:"2:41",
    views:"1M",
    uploadDate:"2021",
    videoURL:"https://www.youtube.com/watch?v=C48-6GopS1c",
    blueTick:true,
    subscribers:"248k",
    categoryName:"LGBTQ+ Story",
    channelImg:"https://yt3.ggpht.com/ytc/AKedOLT81nHF2AA6BnFPBN6_IoOY3mKSl6vk2VcICtHYIQ=s48-c-k-c0x00ffffff-no-rj",
  },
];
